baseurl = "https://cloudnativedevopsblog.com/"
languageCode = "en-us"
title = "Cloud Native DevOps Blog"
theme = "purehugo"
Paginate = 10

[params]
  githubName = "cloudnativedevops"
  description = "Cloud Native DevOps blog"
  google_analytics = "UA-113693326-1"
  twitterName = "cloudnatived"
  hideShareOptions = true

[permalinks]
    post = "/:title"
