apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
